[masters]
k8s-master-01 ansible_host=192.168.1.10 ansible_user=root # ansible_password=PLACEHOLDER_PASSWORD

[workers]
k8s-node-01 ansible_host=192.168.1.11 ansible_user=root # ansible_password=PLACEHOLDER_PASSWORD
k8s-node-02 ansible_host=192.168.1.12 ansible_user=root # ansible_password=PLACEHOLDER_PASSWORD
k8s-node-03 ansible_host=192.168.1.13 ansible_user=root # ansible_password=PLACEHOLDER_PASSWORD

[k3s_cluster:children]
masters
workers

[k3s_cluster:vars]
ansible_python_interpreter=/usr/bin/python3
