---
- hosts: "masters"
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Install K3s on Master
      shell: |
        curl -sfL https://get.k3s.io | sh -s - server \
        --disable traefik \
        --write-kubeconfig-mode 644
      register: k3s_install
      changed_when: "'k3s' not in k3s_install.stdout"

    - name: Get Node Token
      command: cat /var/lib/rancher/k3s/server/node-token
      register: node_token

- hosts: "workers"
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Join K3s Workers
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars[groups['masters'][0]]['ansible_host'] }}:6443 \
        K3S_TOKEN={{ hostvars[groups['masters'][0]]['node_token']['stdout'] }} sh -
      register: k3s_join
      changed_when: "'k3s' not in k3s_join.stdout"
