---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: podinfo
  namespace: podinfo 
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/orenzp/podinfo

